name: flutter_widget_from_html
version: 0.1.0
description: Flutter plugin for widget tree building from html that supports hyperlink, image, nested list, etc. 
author: Dao Hoang Son <daohoangson@gmail.com>
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  cached_network_image: ^0.5.0
  flutter:
    sdk: flutter
  flutter_widget_from_html_core:
    path: ./packages/core
  flutter_youtube_player:
    path: ./packages/youtube_player
  url_launcher: ^4.0.0

# https://github.com/renefloor/flutter_cache_manager/issues/48
dependency_overrides:
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  html: ^0.13.3
