name: flutter_youtube_player
version: 0.1.0
description: Flutter plugin for YouTube player widget using unofficial YouTube api.
author: Dao Hoang Son <daohoangson@gmail.com>
homepage: https://github.com/daohoangson/flutter_widget_from_html/tree/master/packages/youtube_player

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  cached_network_image: ^0.5.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^0.2.0
  url_launcher: ^4.0.0
  video_player: ^0.7.2

# https://github.com/renefloor/flutter_cache_manager/issues/48
dependency_overrides:
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
